Load Libraries
```{r}
library(dlm)
library(tseries)
library(tidyverse)
library(ggplot2)
library(forecast)


setwd("~/IMPORTANT_FILES/Bocconi/YR2SEM2/Time Series/Assignment_1")
df <- read.table("gistemp.txt", header = TRUE, sep = ",")
```

Functions
```{r}
## Function takes dataframe and returns timeseries object
TimeSeries = function(start_year, end_year, df){
  matrix = as.matrix(df[, 2:13])
  tsvector = as.vector(t(matrix))
  ts = ts(data = tsvector, freq = 12, start = c(1880,1))
  return(window(ts,
                start = c(start_year, 1),
                end = c(end_year, 12)))
} 

## Function that takes decomposed ts object and returns a dataframe
DecomposedDF = function(start_year, end_year, df, method = "decompose", t=NULL, s = "periodic"){
  if (method == "decompose"){
    dc = decompose(TimeSeries(start_year, 
                              end_year, 
                              df),
                   type = "additive")
    dc$remainder = dc$random
  } 
  else if (method == "stl"){
    dc = stl(TimeSeries(start_year, 
                        end_year, 
                        df), 
             s.window = s,
             t.window = t)
    dc = as.data.frame(dc$time.series)
    dc$x = as.vector(TimeSeries(start_year, 
                                end_year, 
                                df))
  }
  month = rep(month.abb, length.out = length(TimeSeries(start_year,
                                                        end_year,
                                                        df)))
  month_n = rep(1:12, length.out = length(TimeSeries(start_year, 
                                                     end_year, 
                                                     df)))
  year = rep(c(start_year:end_year), each=12)
  original = as.vector(dc$x)
  seasonal = as.vector(dc$seasonal)
  trend = as.vector(dc$trend)
  residual = as.vector(dc$remainder)
  
  dfnew = data.frame(year, month, month_n, original, seasonal, trend, residual)
  
  dfnew = dfnew %>% mutate(weather_season = case_when(
    month %in% c("Dec", "Jan", "Feb") ~ "Wi",
    month %in% c("Mar", "Apr", "May") ~ "Sp",
    month %in% c("Jun", "Jul", "Aug") ~ "Su",
    month %in% c("Sep", "Oct", "Nov") ~ "Fa"
  )) %>% mutate(date = paste(year, month_n, "01", sep = "-"))
  
  dfnew$date2 = as.Date(dfnew$date)
  
  return(dfnew)
}


## Function returns graph of fitted seasonality, trend, and residuals.
f = function(start_year, end_year, df, yr=c(0), graph = "seasonal", color = FALSE, method = "decompose", t=NULL, s = "periodic"){
  
  dfnew = DecomposedDF(start_year,
                       end_year,
                       df = df, 
                       method = method,
                       t=t,
                       s=s)
  dfnew2 = dfnew %>% filter(year %in% yr)

  if (color == TRUE){
    if (any(yr == c(0))) {
      return(ggplot(dfnew, aes(x = date2, 
                               y = !!sym(graph), 
                               color = weather_season,
                               group = 1)) + 
      geom_line() + 
      scale_color_manual(values = c('Wi' = "blue",
                                  'Sp' = "green",
                                  'Su' = "red",
                                  'Fa' = "black")) +
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())
    }
    else {
      return(ggplot(dfnew2, aes(x = date2, 
                                y = !!sym(graph), 
                                color = weather_season, 
                                group = 1)) + 
      geom_line() +
      scale_color_manual(values = c('Wi' = "blue",
                                    'Sp' = "green",
                                    'Su' = "red",
                                    'Fa' = "black")) + 
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())  
    }
    }
  else if (color == FALSE){
    if (any(yr == c(0))) {
      return(ggplot(dfnew, aes(x = date2, 
                               y = !!sym(graph))) + 
      geom_line(color = "blue") + 
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())
    }
    else {
      return(ggplot(dfnew2, aes(x = date2, 
                                y = !!sym(graph))) + 
      geom_line(color = "blue") +
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())  
    }
  }
}
```

Specific Plots
```{r, fig.width=20, fig.height=5}
df <- read.table("gistemp.txt", header = TRUE, sep = ",")

"Plot of Seasonality"



"Plot of Trend"
f(start_year = 1880,
  end_year = 2024,
  df=df, 
  graph = "seasonal", 
  color = TRUE,
  method = "stl",
  t=151,
  s = 7,
  yr = c(0))

plot(decompose(TimeSeries(start_year= 1880, end_year = 1930, df)))

plot(stl(TimeSeries(start_year = 1880, end_year = 2024, df), s.window = 7, t.window = 151))

f(start_year = 1880,
  end_year = 2024,
  df = df, 
  yr = c(2001:2015), 
  graph = "original", 
  color = TRUE,
  method = "stl",
  t = 151,
  s = 11)


```


```{r}

year_vector0 = df$Year
year_vector4 = c(1880:1930)

df2 = DecomposedDF(year_vector = year_vector4, df=df, method = "stl")
df3 = DecomposedDF(year_vector = year_vector0, df=df, method = "stl")

df3 = df3 %>% filter(year %in% c(1931:1940)) 

HW_temp = HoltWinters(ts(na.omit(df2$trend), freq = 12)) 
HW_temp_forecast = forecast(HW_temp, h = 120)

df3 = df3 %>% mutate(forecasted_trend = HW_temp_forecast$mean)

plot(x = df3$date2, y = df3$trend, type = "l", col = "red")
lines(x = df3$date2, y = df3$forecasted_trend, col = "blue")

plot(x = df3$date2, y = df3$forecasted_trend, lty=2, col = "blue")
```


HoltWinters Forecasted Trend
```{r}

t = 151
s = 7

################# Original Extracted Trend
temp_stl_original = stl(TimeSeries(start_year = 1880,
                                   end_year = 2024,
                                   df = df),
                        s.window = "periodic")
temp_trend_original = temp_stl_original$time.series[,2]

################# No Initial Start Values 
temp_1930 = TimeSeries(start_year = 1880,
                              end_year = 1930,
                              df = df)
temp_1930_stl = stl(temp_1930, 
                    s.window = s,
                    t.window = t)
HW_1930 = HoltWinters(temp_1930_stl$time.series[,2])
HW_1930_forecast = forecast(HW_1930, h = 40)
HW_1930_onestep = HW_1930$fitted[,1]

################# Different Initial Start Values
temp_1930 = TimeSeries(start_year = 1880,
                              end_year = 1930,
                              df = df)
temp_1930_stl = stl(temp_1930, 
                    s.window = s,
                    t.window = t)
HW_1930_diff = HoltWinters(temp_1930_stl$time.series[,2],
                        optim.start = c(0,0.2,0.2))
HW_1930_forecast_diff = forecast(HW_1930_diff, h = 1000)
HW_1930_onestep_diff = HW_1930_diff$fitted[,1]

plot(temp_trend_original)
lines(HW_1930_forecast_diff$mean, col = "green")
lines(HW_1930_onestep_diff, col = "blue")
```


```{r}
temp_stl_original = stl(TimeSeries(start_year = 1880,
                                   end_year = 1930,
                                   df = df),
                        s.window = "periodic",
                        t.window = 101)
plot(temp_stl_original)


```


HoltWinters Forecasted Original
```{r}
################# Original Extracted Trend
temp_original = TimeSeries(start_year = 1880,
                                   end_year = 2024,
                                   df = df)

################# No Initial Start Values 
temp_1930 = TimeSeries(start_year = 1880,
                              end_year = 1930,
                              df = df)
HW_1930 = HoltWinters(temp_1930)
HW_1930_forecast = forecast(HW_1930, h = 40)
HW_1930_onestep = HW_1930$fitted[,1]

################# Different Initial Start Values
temp_1930 = TimeSeries(start_year = 1880,
                              end_year = 1930,
                              df = df)
HW_1930_diff = HoltWinters(temp_1930,
                      seasonal = "additive",
                      optim.start = c(0,0,0))
HW_1930_forecast_diff = forecast(HW_1930_diff, h = 1000)
HW_1930_onestep_diff = HW_1930_diff$fitted[,1]

plot(temp_original)
lines(HW_1930_forecast_diff$mean, col = "blue")
lines(HW_1930_onestep_diff, col = "green")
```





































