


```{r}
library(dlm)
library(tseries)
library(tidyverse)
library(ggplot2)

setwd("~/IMPORTANT_FILES/Bocconi/YR2SEM2/Time Series/Assignment_1")
df <- read.table("gistemp.txt", header = TRUE, sep = ",")
```



```{r, fig.width=20, fig.height=10}

year_vector0 = df$Year

dc2 = stl(TimeSeries(year_vector0, df), s.window = 'periodic')
dc2 = as.data.frame(dc2$time.series)
dc2$x = as.vector(TimeSeries(year_vector0, df))

f = function(year_vector, df, yr=c(0), graph = "seasonal", color = FALSE, method = "decompose"){
  
  if (method == "decompose"){
    dc = decompose(TimeSeries(year_vector, df), type = "additive")
    dc$remainder = dc$random
  } 
  else if (method == "stl"){
    dc = stl(TimeSeries(year_vector0, df), s.window = 'periodic')
    dc = as.data.frame(dc$time.series)
    dc$x = as.vector(TimeSeries(year_vector0, df))
  }
  
  month = rep(month.abb, length.out = length(TimeSeries(year_vector, df)))
  month_n = rep(1:12, length.out = length(TimeSeries(year_vector, df)))
  year = rep(year_vector, each=12)
  original = as.vector(dc$x)
  seasonal = as.vector(dc$seasonal)
  trend = as.vector(dc$trend)
  residual = as.vector(dc$remainder)
  
  dfnew = data.frame(year, month, month_n, original, seasonal, trend, residual)
  
  dfnew = dfnew %>% mutate(weather_season = case_when(
    month %in% c("Dec", "Jan", "Feb") ~ "Wi",
    month %in% c("Mar", "Apr", "May") ~ "Sp",
    month %in% c("Jun", "Jul", "Aug") ~ "Su",
    month %in% c("Sep", "Oct", "Nov") ~ "Fa"
  )) %>% mutate(date = paste(year, month_n, "01", sep = "-"))
  
  dfnew$date2 = as.Date(dfnew$date)
  dfnew2 = dfnew %>% filter(year %in% yr)

  if (color == TRUE){
    if (any(yr == c(0))) {
      return(ggplot(dfnew, aes(x = date2, 
                               y = !!sym(graph), 
                               color = weather_season,
                               group = 1)) + 
      geom_line() + 
      scale_color_manual(values = c('Wi' = "blue",
                                  'Sp' = "green",
                                  'Su' = "red",
                                  'Fa' = "black")) +
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())
    }
    else {
      return(ggplot(dfnew2, aes(x = date2, 
                                y = !!sym(graph), 
                                color = weather_season, 
                                group = 1)) + 
      geom_line() +
      scale_color_manual(values = c('Wi' = "blue",
                                    'Sp' = "green",
                                    'Su' = "red",
                                    'Fa' = "black")) + 
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())  
    }
    }
  else if (color == FALSE){
    if (any(yr == c(0))) {
      return(ggplot(dfnew, aes(x = date2, 
                               y = !!sym(graph))) + 
      geom_line(color = "blue") + 
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())
    }
    else {
      return(ggplot(dfnew2, aes(x = date2, 
                                y = !!sym(graph))) + 
      geom_line(color = "blue") +
      labs(x = "month", y = "Seasonal Fit") + 
      theme_minimal())  
    }
  }
}

f(year_vector = year_vector0, 
  df = df, 
  yr = c(2000:2003), 
  graph = "original", 
  color = FALSE,
  method = "decompose")

```

